version: '3.8'
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
      - ./redis.conf:/etc/redis.conf
    command: 'redis-server /etc/redis.conf'
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=123456789
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/data
      - ./config:/root/.minio
    command: server /data --console-address ":9090" -address ":9000"
  es:
    image: elasticsearch:7.12.1
    user: root
    container_name: es
    networks:
      - es
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./data:/usr/share/elasticsearch/data
      - ./plugins:/usr/share/elasticsearch/plugins
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./data:/var/lib/mysql
  zdx-blog-plus:
    build: ./Dockerfile
    container_name: zdx-blog-plus
    ports:
      - "8888:8888"
    volumes:
      - ./log:/home/zdx/logs
    depends_on:
      - es
      - mysql
      - minio
      - redis
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - "./zdx-admin-ui/dist/*:/usr/share/nginx/html/admin"
      - ./zdx-ui/dist/*:/usr/share/nginx/html/home

networks:
  es:
    external:
      name: es