spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456789
    url: jdbc:mysql://localhost:3306/zdx-blog-plus?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 20MB
  mvc:
    path match:
      matching-strategy: ant_path_matcher
mybatis-plus:
  global-config:
    banner: false
zdx:
  common:
    cache: redis
  oss:
    oss-type: minio
  es:
    open: true
    url: http://81.69.247.228:9200
    username: elastic
    password: zdx@123456
    index: dev_articles
logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint}%L %m%n%wEx'
  level:
    com.zdx.mapper: debug

knife4j:
  enable: true
  setting:
    language: zh-CN