spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: xxxxx
    url: jdbc:mysql://192.168.0.104:3306/zdx-blog-plus?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    druid:
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        login-username: admin
        login-password: xxxxx
        allow: ""
      web-stat-filter:
        enabled: true
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  mail:
    host: smtp.qq.com
    username: 2488288090@qq.com
    password: xxxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 20MB

  mvc:
    path match:
      matching-strategy: ant_path_matcher
  redis:
    lettuce:
      pool:
        enabled: true
    host: 192.168.0.104
mybatis-plus:
  global-config:
    banner: false
logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint}%L %m%n%wEx'
  level:
    com.zdx.mapper: debug
knife4j:
  enable: true
  setting:
    language: zh-CN

---
zdx:
  common:
    xss-excludes: false
    sensitive-excludes: false
  oss:
    oss-type: minio
    url: https://static.zhaodengxuan.top
    access-key: xxxxx
    secret-key: xxxxx
    username: admin
    password: xxxxx
  es:
    open: true
    url: http://81.69.247.228:9200
    username: elastic
    password: xxxxx
    index: dev_articles